# Generated by Django 5.0.4 on 2024-04-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_emer', models.CharField(blank=True, max_length=50, null=True)),
                ('item_images', models.ImageField(blank=True, null=True, upload_to='item1/')),
            ],
        ),
    ]
