# Generated by Django 5.0.4 on 2024-04-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='surname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
